-- setup_azure_integration.sql
-- One-time setup that lets Snowflake read the ADLS Gen2 "raw" landing zone
-- (populated by pipeline/adls.py) via an EXTERNAL STAGE.
--
-- APPROACH: SAS token, NOT a Snowflake STORAGE INTEGRATION.
--   A storage integration would require the Azure AD tenant ID plus an Azure
--   Portal consent + "Storage Blob Data Reader" role grant on the service
--   principal. We do not have Portal access or the tenant ID, so instead we
--   authenticate the stage with a container-scoped SAS token (read + list)
--   generated locally from the storage account key. No integration object,
--   no tenant ID, no consent flow is needed.
--
-- SECRET HANDLING (important):
--   The AZURE_SAS_TOKEN below is a PLACEHOLDER. The real token is a live
--   read/list credential and must NEVER be committed. It lives only in the
--   gitignored .env (key: AZURE_SAS_TOKEN). Substitute the real value at
--   execution time (the runner that applies this script reads it from .env);
--   do not paste the real token into this file.
--
-- The SAS token is generated with:
--   azure.storage.blob.generate_container_sas(
--       container_name="raw", permission=ContainerSasPermissions(read, list),
--       expiry=now + 90 days)
--   parsing account_name/account_key out of AZURE_STORAGE_CONNECTION_STRING.
--   Regenerate before the ~90-day expiry and re-run the CREATE STAGE.
--
-- Run this in the database configured in .env (the one that owns the BRONZE
-- schema). Uncomment and set the USE statements if not already in context.

-- USE DATABASE <your_database>;   -- e.g. the SNOWFLAKE_DATABASE from .env
-- USE SCHEMA BRONZE;

-- Step 1: External stage over the ADLS "raw" container, authenticated by SAS.
--   URL uses the blob endpoint (…blob.core.windows.net) to match the
--   container SAS generated by the blob SDK.
--   STRIP_OUTER_ARRAY = TRUE because pipeline/adls.py writes each landed file
--   as a single JSON array (json.dumps(list_of_records)); this makes COPY INTO
--   expand each array element into its own row instead of one row per file.
CREATE OR REPLACE STAGE bronze.azure_raw_stage
  URL = 'azure://jobmarketadls2026.blob.core.windows.net/raw/'
  CREDENTIALS = (AZURE_SAS_TOKEN = '<REPLACE_WITH_SAS_TOKEN>')
  FILE_FORMAT = (TYPE = JSON STRIP_OUTER_ARRAY = TRUE);

-- Step 2 (verification, run manually): confirm the stage is defined and that
-- Snowflake can see the files the pipeline already uploaded. File names only.
-- DESC STAGE bronze.azure_raw_stage;
-- LIST @bronze.azure_raw_stage;
